[package]
name = "matrix-sdk-sql"
version = "0.1.0-beta.2"
edition = "2021"
authors = ["Charlotte 🦝 Delenk <lotte@chir.rs>"]
rust-version = "1.62.0"
description = "SQL-Based State Storage for matrix-sdk"
readme = "README.md"
repository = "https://github.com/DarkKirb/matrix-sdk-statestore-sql"
license = "Apache-2.0"
keywords = ["matrix", "sql"]
categories = ["database", "caching"]

[features]
default = ["native-tls", "postgres"]

native-tls = ["sqlx/runtime-tokio-native-tls"]
rustls = ["sqlx/runtime-tokio-rustls"]

postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]

e2e-encryption = [
    "dep:bincode",
    "dep:dashmap",
    "dep:educe",
    "matrix-sdk-base/e2e-encryption",
    "dep:matrix-sdk-crypto",
    "dep:matrix-sdk-store-encryption",
    "dep:parking_lot",
    "dep:serde",
    "dep:vodozemac",
]

# Internal feature used by ci builds
ci = []

[dependencies]
async-trait = "0.1.53"
bincode = { version = "1.3.3", optional = true }
dashmap = { version = "5.2.0", optional = true }
futures = "0.3.21"
matrix-sdk-base = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "561fb97a7b2235a198f6ae45a04cea9c0153fb44" }
matrix-sdk-crypto = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "561fb97a7b2235a198f6ae45a04cea9c0153fb44", optional = true }
matrix-sdk-store-encryption = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "561fb97a7b2235a198f6ae45a04cea9c0153fb44", optional = true }
parking_lot = { version = "0.12.0", optional = true }
ruma = { git = "https://github.com/ruma/ruma", rev = "284b797e0513daf56859b64b8c7a506856fb11ec" }
serde = { version = "1.0.137", features = ["derive"], optional = true }
serde_json = { version = "1.0.81" }
thiserror = "1.0.31"
vodozemac = { version = "0.3.0", optional = true }
tracing = "0.1.37"

[dependencies.educe]
version = "0.4.19"
default-features = false
features = ["Debug"]
optional = true

[dependencies.sqlx]
version = "0.6.0, <0.6.2"      # 0.6.2 is a breaking change
features = ["migrate", "json"]

[dependencies.sqlx-core]
version = "0.6.0, <0.6.2"

[dev-dependencies.tokio]
version = "1.18.1"
features = ["macros", "rt-multi-thread"]
default-features = false

[dev-dependencies]
ctor = "0.1.26"
matrix-sdk-base = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "561fb97a7b2235a198f6ae45a04cea9c0153fb44", features = ["testing"] }
matrix-sdk-crypto = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "561fb97a7b2235a198f6ae45a04cea9c0153fb44", features = ["testing"] }
matrix-sdk-test = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "561fb97a7b2235a198f6ae45a04cea9c0153fb44" }
once_cell = "1.10.0"
rand = "0.8.5"
tempfile = "3.3.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
