[package]
name = "matrix-sdk-ffi"
version = "0.2.0"
edition = "2021"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ffi"]
license = "Apache-2.0"
readme = "README.md"
rust-version = { workspace = true }
repository = "https://github.com/matrix-org/matrix-rust-sdk"

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
default = []
jaeger-rageshakes = [
    "dep:async-compression",
    "dep:opentelemetry",
    "dep:opentelemetry-jaeger",
    "dep:opentelemetry-contrib",
    "dep:tokio-tar",
    "dep:tracing-opentelemetry",
]

[build-dependencies]
uniffi_build = { workspace = true, features = ["builtin-bindgen"] }

[dependencies]
anyhow = { workspace = true }
async-compression = { version = "0.3.15", features = ["tokio", "zstd"], optional = true }
extension-trait = "1.0.1"
futures-core = "0.3.17"
futures-signals = { version = "0.3.30", default-features = false }
futures-util = { version = "0.3.17", default-features = false }
mime = "0.3.16"
# FIXME: we currently can't feature flag anything in the api.udl, therefore we must enforce experimental-sliding-sync being exposed here..
# see https://github.com/matrix-org/matrix-rust-sdk/issues/1014
once_cell = { workspace = true }
opentelemetry = { version = "0.18.0", optional = true }
opentelemetry-contrib = { version = "0.10.0", features = ["jaeger_json_exporter", "rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.17.0", optional = true }
sanitize-filename-reader-friendly = "2.2.1"
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.8"
tokio-tar = { version = "0.3.0", optional = true }
tracing-opentelemetry = { version = "0.18.0", optional = true }
uniffi = { workspace = true }
uniffi_macros = { workspace = true }
zeroize = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
tracing = { version = "0.1.29", default-features = false, features = ["log"] }
android_logger = "0.11"
log-panics = { version = "2", features = ["with-backtrace"] }
matrix-sdk = { path = "../../crates/matrix-sdk", default-features = false, features = ["anyhow", "experimental-timeline", "e2e-encryption", "sled", "markdown", "experimental-sliding-sync", "socks", "rustls-tls"], version = "0.6.0" }

[target.'cfg(not(target_os = "android"))'.dependencies]
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
matrix-sdk = { path = "../../crates/matrix-sdk", features = ["anyhow", "experimental-timeline", "markdown", "experimental-sliding-sync", "socks"], version = "0.6.0" }
