name: "Kotlin: Build & Publish snapshot"

on:
  workflow_dispatch:
    inputs:
      rust-checkout-ref:
        description: 'The branch, tag or SHA to build the kotlin sdk from'     
        required: true
        default: 'main'
  pull_request:

jobs:
  build_native:
    name: Build and generate crypto native libs
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - name: armv7
            target: armv7-linux-androideabi
            jni-folder: armeabi-v7a
          - name: i869
            target: i686-linux-android
            jni-folder: x86
          - name: Aarch64
            target: aarch64-linux-android
            jni-folder: arm64-v8a
        
    steps:
      # for testing only
      - name: Checkout this repo
        uses: actions/checkout@v3
        if: ${{ !github.event.inputs.rust-checkout-ref }}
    
      - name: Checkout this repo
        uses: actions/checkout@v3
        if: ${{ github.event.inputs.rust-checkout-ref }}
        with: 
          ref: '${{ github.event.inputs.rust-checkout-ref }}'
    
      - name: Install android sdk
        uses: malinskiy/action-android/install-sdk@release/0.1.2
        
      - name: Install android ndk   
        uses: nttld/setup-ndk@v1
        id: install-ndk
        with:
          ndk-version: r22b
          
      - name: Create symlinks for buildchain
        run: |
          export PATH="${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin:$PATH"
          echo $PATH
    
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: stable
          override: true

      - name: Cargo install uniffi_bindgen
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: uniffi_bindgen    

      - name: Cargo build    
        uses: actions-rs/cargo@v1
        env: 
          ANDROID_NDK: ${{ steps.install-ndk.outputs.ndk-path }}

          # AARCH64 build env
          CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android30-clang
          CARGO_TARGET_AARCH64_LINUX_ANDROID_AR: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar
          AR_aarch64_linux_android: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar
          CC_aarch64_linux_android: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android30-clang

          # I686 build env
          CARGO_TARGET_I686_LINUX_ANDROID_LINKER: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android30-clang
          CARGO_TARGET_I686_LINUX_ANDROID_AR: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar
          AR_i686_linux_android: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar
          CC_i686_linux_android: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android30-clang

          # ARMV7 build env
          CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi30-clang
          CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_AR: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar
          AR_armv7_linux_android: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar
          CC_armv7_linux_android: ${{ steps.install-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi30-clang
        with:
          command: build
          args: --manifest-path bindings/matrix-sdk-crypto-ffi/Cargo.toml --release --target=${{ matrix.target }}
          
      - name: Rename native file
        run: |
          mv target/${{ matrix.target }}/release/matrix_crypto_ffi.so target/${{ matrix.target }}/release/libuniffi_olm.so
          
      - name: Upload native file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.jni-folder }}
          path: target/${{ matrix.target }}/release/libuniffi_olm.so
   
  build_android:
    name: Build and publish android library 
    runs-on: macos-latest
    needs: build_native
    env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        SNAPSHOT: true

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    
    - name: Create jniLibs folder
      run: |
          mkdir -p bindings/kotlin/crypto/crypto-android/src/main/jniLibs   
          
    - name: Download all binary result
      uses: actions/download-artifact@v2
      with:
        path: bindings/kotlin/crypto/crypto-android/src/main/jniLibs
    
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-
  
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
            
    - name: Cargo install uniffi_bindgen
      continue-on-error: true
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: uniffi_bindgen    
    
    - name: Generate bindings
      run: |
        uniffi-bindgen generate bindings/matrix-sdk-crypto-ffi/src/olm.udl  --language kotlin --out-dir bindings/kotlin/crypto/crypto-android/build/generated/source/uniffi/release/java
    
    - name: Grant execute permission for gradlew
      working-directory: bindings/kotlin
      run: chmod +x gradlew
      
    - name: Build crypto module
      working-directory: bindings/kotlin
      run: ./gradlew :crypto:crypto-android:assembleRelease
      
    - name: Upload library file (aar)
      uses: actions/upload-artifact@v2
      with:
        name: crypto-release
        path: bindings/kotlin/crypto/crypto-android/build/outputs/aar/crypto-android-release.aar
  
    - name: Publish to MavenCentral
      working-directory: bindings/kotlin
      run: ./gradlew publishReleasePublicationToSonatypeRepository
